baseURL = "http://queroficar.fit"
languageCode = "pt-br"
title = "QueroFicar.fit"
theme = "hugo-theme-blog"
paginate = 10

[params]
logo = "images/logo.svg"
cover = "images/cover.jpg"
description = "Site com treinos e exercícios para entrar em forma e ficar saudável, além de receitas e dietas para se alimentar bem"
keywords = [ 
  "fit", "fitness", "esportes", "alimentação", "saudável", "dietas", 
  "receitas", "atividades físicas", "treinos", "musculação", "academia", 
  "motivação", "emagrecer", "calorias", "saúde", "bem-estar" ]
themeColor = "deep-purple"
analyticsId = "UA-115830905-1"
adsenseSlot = "7050788775"
adsenseClient = "ca-pub-7523733879032648"
disqusShortname = ""
disqusLanguage = "pt_BR"
showPostDate = false

[[menu.main]]
name = "QueroFicar.fit"
pre = "home"
url = "/"
weight = 1

[[menu.main]]
name = "Categorias"
pre = "turned-in-not"
url = "/categories"
weight = 2

[[menu.main]]
name = "Hashtags"
pre = "hashtag"
url = "/tags"
weight = 3

[[menu.main]]
name = "Sobre"
pre = "info-outline"
url = "/about"
weight = 4

[related]
threshold = 80
includeNewer = true
toLower = false

[[related.indices]]
name = "categories"
weight = 150
[[related.indices]]
name  = "tags"
weight = 100
[[related.indices]]
name  = "date"
weight = 10
pattern = "2006"
